### ISSUE TITLE
Shipping Addon data not being stored

### ISSUE THREAD

**Issue by ZeoNull** [strangerstudios/pmpro-shipping#1]
The shipping add-on does not seem to hold any of the data the user enters when registering. 

The form show up on the checkout page but fields are empty in member profile.

**Comment by glaeserd** [comment]
I am also having the same issue! I am using Paypal standard as well

**Comment by strangerstudios** [comment]
This issue should be fixed now with PayPal Standard. Open a new issue if you are still having trouble.
