### ISSUE TITLE
Phone number missing from shipping fields

### ISSUE THREAD

**Issue by efc** [strangerstudios/pmpro-shipping#13]
Even though the phone number is part of the billing address in PMPro, there is no corresponding pmpro_sphone field in the Shipping Address Add On. This means that the phone number included in the billing address is not placed anywhere in user meta. This appears to be an oversight, since the makes a copy of all other billing information into user meta.

**Comment by femiyb** [comment]
Fix for this https://github.com/strangerstudios/pmpro-shipping/pull/22
