### ISSUE TITLE
Improve compatibility with PMPro State Dropdowns Add On

### ISSUE THREAD

**Issue by greathmaster** [strangerstudios/pmpro-shipping#14]
When the PMPro State Dropdowns Add On is active and the checkbox for "Ship to the billing address used above." is selected, the error message "Please complete all required fields." is displayed.

It appears the dropdown shipping select field is not being copied from the billing address state field.

**Comment by andrewlimaza** [comment]
I've done a work-around with some jQuery on the pmpro-shipping.js around line 30, before `var self = this ` ( temp workaround, not the best )-> 

`
	jQuery('#scountry').val( jQuery('#bcountry').val() );
        	jQuery('#sstate').replaceWith( '<input type="text" id="sstate"></input>');
        	jQuery('#sstate').val( jQuery('#bstate').val() );
`

Convert the state dropdown to text and manually copy the bcountry over.

For some reason the loop wasn't considering the bcountry field for some weird reason.

Hope this helps to anyone that sees this :)

**Comment by dparker1005** [comment]
Workaround above now works with out changing the dropdown to a textfield:
```
jQuery('#scountry').val( jQuery('#bcountry').val() ); 
jQuery('#sstate').val( jQuery('#bstate').val() );
```

Note: Only copies billing info to shipping info when the checkbox is clicked, so checking box and then choosing state still has an issue.

**Comment by web-agent-github** [comment]
The above solution worked for me. Thank you for your prompt solution dparker1005. Legend.

Will this be updated in the next update so that my solution will not be wiped on next update?

**Comment by andrewlimaza** [comment]
This will be available in the next update. I'll close this issue as it's been resolved.

Thank you for your patience and understanding.

**Comment by web-agent-github** [comment]
Cheers Andrew.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
