### ISSUE TITLE
Country field in Shipping section overwrites Billing Section even when "Same as Billing Address" is selected

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-shipping#17]
When a user selects the "Same as Billing Address" for Shipping Address it does not honor the Country Field. It changes the Country to United States or whatever country is set on the country field in the Shipping Address section.

https://www.paidmembershipspro.com/forums/topic/shipping-address-same-as-billing-address/

**Comment by andrewlimaza** [comment]
Test this PR - https://github.com/strangerstudios/pmpro-shipping/pull/21

**Comment by andrewlimaza** [comment]
This works with latest version :)
