### ISSUE TITLE
Phone number entered not picked up during required field check

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-shipping#28]
When using PayPal Express as a live/production gateway the field for phone number returns a "Please complete all required fields" even when not empty. The value for this field is not returned on submit or saved to the database.

**Comment by ipokkel** [comment]
Fix here https://github.com/strangerstudios/pmpro-shipping/pull/30

**Comment by andrewlimaza** [comment]
This has been merged in latest commit and will be released with next version.
