### ISSUE TITLE
Required shipping fields return null

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-shipping#29]
Array key values are set with undefined variables.

https://github.com/strangerstudios/pmpro-shipping/blob/ca90261d05cf4bf778e7b1eb7f8818384cda08c1/pmpro-shipping.php#L424-L433

The solution for this is to call these variables beforehand as globals, e.g.
`global $sfirstname, $slastname, $saddress1, $scity, $sstate, $szipcode, $sphone, $scountry;`

**Comment by ipokkel** [comment]
Fix here: https://github.com/strangerstudios/pmpro-shipping/pull/31

**Comment by andrewlimaza** [comment]
This has been merged in latest commit and will be released with next version.
