### ISSUE TITLE
The "Ship to the billing address used above" checkbox doesn't hide the shipping address fields.

### ISSUE THREAD

**Issue by UnlokMedia** [strangerstudios/pmpro-shipping#43]
I tried to workaround with a code module using this script:

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js">
$(function () {
        $("#sameasbilling").click(function () {
            if ($(this).is(":checked")) {
  		$("#shipping-fields").addClass('shipping-hider');
            } else {
                $("#shipping-fields").removeClass('shipping-hider');
            }
        });
    });
</script>

<style>
  
.shipping-hider{display: none !Important;}
  
</style>
```

But I can't seem to get it to work.

The shipping fields hide successfully if the user tries to submit without filling in some required fields, where the page refreshes with the warning and the shipping fields are hidden

**Comment by UnlokMedia** [comment]
*SOLVED*

Fixed this by adding `onchange="valueChanged()" <?` to the checkbox on line 40 of pmpro-shipping.php.

Then used this javascript:

```
<script type="text/javascript">

    function valueChanged() {
      if (document.getElementById('sameasbilling').checked) {
          document.getElementById("shipping-fields").style.display = 'none';
      } else {
        document.getElementById("shipping-fields").style.display = 'block';
      }
    }

</script>
```

**Comment by andrewlimaza** [comment]
I am unable to replicate this issue. I do see that this issue is over a year old. If you are still experiencing this issue with the latest version of the Shipping Address Add On please let us know.
